In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [2]:
dataset=pd.read_csv("preprocessed_house_rent.csv")

In [3]:
dataset

,BHK,Rent,Size,Area Type,Furnishing Status,Tenant Preferred,Bathroom,City_Chennai,City_Delhi,City_Hyderabad,City_Kolkata,City_Mumbai,Floor Number,Total Floors
0,2,10000,1100,2,2,1,2,0,0,0,1,0,0,2
1,2,20000,800,2,1,1,1,0,0,0,1,0,1,3
2,2,17000,1000,2,1,1,1,0,0,0,1,0,1,3
3,2,10000,800,2,2,1,1,0,0,0,1,0,1,2
4,2,7500,850,1,2,0,1,0,0,0,1,0,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4741,2,15000,1000,1,1,1,2,0,0,1,0,0,3,5
4742,3,29000,2000,2,1,1,3,0,0,1,0,0,1,4
4743,3,35000,1750,1,1,1,3,0,0,1,0,0,3,5
4744,3,45000,1500,1,1,2,2,0,0,1,0,0,23,34
4745,2,15000,1000,1,2,0,2,0,0,1,0,0,4,5

In [4]:
print(dataset.isnull().sum())

BHK                  0
Rent                 0
Size                 0
Area Type            0
Furnishing Status    0
Tenant Preferred     0
Bathroom             0
City_Chennai         0
City_Delhi           0
City_Hyderabad       0
City_Kolkata         0
City_Mumbai          0
Floor Number         0
Total Floors         0
dtype: int64

In [5]:
dataset.columns

Index(['BHK', 'Rent', 'Size', 'Area Type', 'Furnishing Status',
       'Tenant Preferred', 'Bathroom', 'City_Chennai', 'City_Delhi',
       'City_Hyderabad', 'City_Kolkata', 'City_Mumbai', 'Floor Number',
       'Total Floors'],
      dtype='object')

In [6]:
independent=dataset[[ 'BHK','Size', 'Area Type', 'Furnishing Status',
       'Tenant Preferred', 'Bathroom', 'City_Chennai', 'City_Delhi',
       'City_Hyderabad', 'City_Kolkata', 'City_Mumbai', 'Floor Number',
       'Total Floors']]

In [7]:
independent

,BHK,Size,Area Type,Furnishing Status,Tenant Preferred,Bathroom,City_Chennai,City_Delhi,City_Hyderabad,City_Kolkata,City_Mumbai,Floor Number,Total Floors
0,2,1100,2,2,1,2,0,0,0,1,0,0,2
1,2,800,2,1,1,1,0,0,0,1,0,1,3
2,2,1000,2,1,1,1,0,0,0,1,0,1,3
3,2,800,2,2,1,1,0,0,0,1,0,1,2
4,2,850,1,2,0,1,0,0,0,1,0,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4741,2,1000,1,1,1,2,0,0,1,0,0,3,5
4742,3,2000,2,1,1,3,0,0,1,0,0,1,4
4743,3,1750,1,1,1,3,0,0,1,0,0,3,5
4744,3,1500,1,1,2,2,0,0,1,0,0,23,34
4745,2,1000,1,2,0,2,0,0,1,0,0,4,5

In [8]:
dependent=dataset[['Rent']]

In [9]:
dependent

       Rent
0     10000
1     20000
2     17000
3     10000
4      7500
...     ...
4741  15000
4742  29000
4743  35000
4744  45000
4745  15000

[4746 rows x 1 columns]

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
independent=sc.fit_transform(independent)

In [11]:
from sklearn.ensemble import RandomForestRegressor

In [12]:
from sklearn.model_selection import GridSearchCV
param_grid={'criterion':["squared_error","absolute_error","friedman_mse","poisson"],
'max_features':["sqrt","log2",None],
'n_estimators':[10,100]}
grid = GridSearchCV(RandomForestRegressor(),param_grid,refit=True,cv=5,verbose=3,n_jobs=-1)
grid.fit(independent,dependent)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

GridSearchCV(cv=5, estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error',
                                       'friedman_mse', 'poisson'],
                         'max_features': ['sqrt', 'log2', None],
                         'n_estimators': [10, 100]},
             verbose=3)

In [13]:
re=grid.cv_results_
grid_predictions = grid.predict(independent)
from sklearn.metrics import r2_score
r_score=r2_score(dependent,grid_predictions)
print("The R_score value for best parameter {}:".format(grid.best_params_),r_score)

The R_score value for best parameter {'criterion': 'absolute_error', 'max_features': 'log2', 'n_estimators': 100}: 0.8898545690261772

In [14]:
table=pd.DataFrame.from_dict(re)

In [15]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.124713,0.007981,0.010486,0.006165,squared_error,sqrt,10,"{'criterion': 'squared_error', 'max_features':...",0.545235,0.256469,-2.397918,0.405530,0.046845,-0.228768,1.097091,14
1,1.066857,0.021003,0.037769,0.007822,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.745288,0.275851,-1.499589,0.330870,-0.062989,-0.042114,0.772644,11
2,0.116520,0.011646,0.009603,0.005792,squared_error,log2,10,"{'criterion': 'squared_error', 'max_features':...",0.697113,0.271892,-0.454589,0.258184,-1.004081,-0.046296,0.605089,12
3,1.052333,0.011972,0.033511,0.002807,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.763161,0.277651,-1.015437,0.365429,-0.045764,0.069008,0.600406,8
4,0.213656,0.009104,0.009375,0.007655,squared_error,None,10,"{'criterion': 'squared_error', 'max_features':...",0.721032,0.282143,-1.891545,-0.408508,-0.636585,-0.386693,0.894639,17
5,2.177218,0.061293,0.047119,0.004993,squared_error,None,100,"{'criterion': 'squared_error', 'max_features':...",0.563169,0.277114,-4.624572,0.343230,0.098749,-0.668462,1.983631,20
6,1.479012,0.065421,0.006829,0.006093,absolute_error,sqrt,10,"{'criterion': 'absolute_error', 'max_features'...",0.777198,0.261356,-0.353736,0.344332,-0.845834,0.036663,0.570044,10
7,15.210913,0.720663,0.047839,0.001334,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.757451,0.279717,-0.598040,0.415556,-0.250864,0.120764,0.484216,5
8,1.481639,0.049839,0.005927,0.006242,absolute_error,log2,10,"{'criterion': 'absolute_error', 'max_features'...",0.704239,0.283275,-1.041389,0.283481,0.267220,0.099365,0.593816,7
9,17.983316,0.513904,0.042324,0.009508,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.776700,0.279710,0.068122,0.434595,-0.146959,0.282434,0.315521,1
10,6.830760,1.244229,0.009376,0.007656,absolute_error,None,10,"{'criterion': 'absolute_error', 'max_features'...",0.754519,0.275028,-5.433917,0.313055,-0.035615,-0.825386,2.317989,21
11,60.134920,4.455542,0.037956,0.012686,absolute_error,None,100,"{'criterion': 'absolute_error', 'max_features'...",0.745883,0.294429,-2.633301,0.315651,-0.123785,-0.280225,1.208274,16
12,0.170824,0.005332,0.007286,0.006272,friedman_mse,sqrt,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.742050,0.264812,-1.111852,0.351347,0.023488,0.053969,0.627122,9
13,1.646582,0.082312,0.059299,0.012121,friedman_mse,sqrt,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.746326,0.279289,-0.892846,0.383662,0.054434,0.114173,0.550847,6
14,0.183266,0.013561,0.017710,0.002352,friedman_mse,log2,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.733800,0.268419,-1.735490,0.269056,-1.699534,-0.432750,1.062721,18
15,1.844454,0.135250,0.062107,0.017904,friedman_mse,log2,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.744252,0.271389,-1.941034,0.344224,0.086688,-0.098896,0.945757,13
16,0.322279,0.009582,0.013568,0.004191,friedman_mse,None,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.548056,0.278074,-4.159064,0.286662,-0.205413,-0.650337,1.771168,19
17,3.148374,0.051755,0.051621,0.006164,friedman_mse,None,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.609986,0.288617,-6.319984,0.406969,-0.105635,-1.024009,2.658247,22
18,0.228887,0.007798,0.009299,0.007938,poisson,sqrt,10,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.723930,0.265789,0.156098,0.282797,-0.599090,0.165905,0.429033,2
19,2.271927,0.067015,0.049334,0.012534,poisson,sqrt,100,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.748374,0.277059,-0.526625,0.397909,-0.173569,0.144630,0.446773,4
20,0.248163,0.029921,0.010481,0.008087,poisson,log2,10,"{'criterion': 'poisson', 'max_features': 'log2...",0.710598,0.274466,-1.922151,-0.312950,-0.072547,-0.264517,0.897586,15
21,2.472692,0.099132,0.050000,0.006253,poisson,log2,100,"{'criterion': 'poisson', 'max_features': 'log2...",0.753976,0.278303,-0.358458,0.381957,-0.268268,0.157502,0.416713,3
22,0.396367,0.012360,0.010856,0.006037,poisson,None,10,"{'criterion': 'poisson', 'max_features': None,...",0.631187,0.279819,-8.007318,0.200645,0.197439,-1.339645,3.337659,23
23,3.819565,0.171019,0.047428,0.014529,poisson,None,100,"{'criterion': 'poisson', 'max_features': None,...",0.671824,0.294104,-8.075412,0.377306,-0.034649,-1.353365,3.368552,24

In [16]:
import pickle
filename="finalized_model_RandomForest.sav"
pickle.dump(grid,open(filename,'wb'))

In [17]:
dataset.columns

Index(['BHK', 'Rent', 'Size', 'Area Type', 'Furnishing Status',
       'Tenant Preferred', 'Bathroom', 'City_Chennai', 'City_Delhi',
       'City_Hyderabad', 'City_Kolkata', 'City_Mumbai', 'Floor Number',
       'Total Floors'],
      dtype='object')

In [18]:
BHK_input=float(input("BHK:"))
Size_input=float(input("Size:"))
Area_Type_input=float(input("Area Type:"))
Furnishing_Status_input = float(input("Furnishing Status:"))
Tenant_Preferred_input=float(input("Tenant Preferred:"))
Bathroom_input=float(input("Bathroom:"))
City_Chennai_input=float(input("City_Chennai:")) 
City_Delhi_input=float(input("City_Delhi:"))     
City_Hyderabad_input=float(input("City_Hyderabad:"))
City_Kolkata_input=float(input("City_Kolkata:")) 
City_Mumbai_input=float(input("City_Mumbai:"))
Floor_Number_input=float(input("Floor_Number':"))
Total_Floors_input=float(input("Total_Floors:"))

BHK: 2
Size: 1100
Area Type: 1
Furnishing Status: 0
Tenant Preferred: 1
Bathroom: 2
City_Chennai: 1
City_Delhi: 1
City_Hyderabad: 0
City_Kolkata: 0
City_Mumbai: 1
Floor_Number': 1
Total_Floors: 2

In [19]:
loaded_model=pickle.load(open("finalized_model_RandomForest.sav",'rb'))

In [20]:
Preinput = sc.fit_transform([[BHK_input, Size_input, Area_Type_input,Furnishing_Status_input,Tenant_Preferred_input,Bathroom_input,City_Chennai_input,City_Delhi_input,City_Hyderabad_input,City_Kolkata_input,City_Mumbai_input,Floor_Number_input,Total_Floors_input]])

In [21]:
Future_Prediction=grid.predict(Preinput)

print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[17787.5]